### ISSUE TITLE
charmcraft actions do not work for tokens with bundle-level scope

### ISSUE THREAD

**Issue by claudiubelu** [finos/waltz-juju-bundle#15]
## Bug Report

Currently, the ``Create release branch`` action [1] is failing because it is not able to publish the bundle on charmhub with the following error:

```
Store operation failed:
- permission-required: Package access not allowed
```

Although the token should have the necessary privileges [1]:

```
name: FINOS Foundation
username: finos-foundation
id: ...
permissions:
- package-view-revisions
- package-manage
charms:
- name: finos-waltz-k8s
bundles:
- name: finos-waltz-bundle
```

### Steps to Reproduce:

This issue is reproduceable on other bundles as well, simply generate a token:

```
charmcraft login --export=secrets-waltz.auth \
      --bundle=finos-waltz-bundle --permission=package-view-revisions \
      --permission=package-manage --ttl=15780000
export CHARMCRAFT_AUTH=`cat ./secrets-waltz.auth`
```

And run:

```
charmcraft revisions finos-waltz-bundle --verbose
```

The same error will occur.

Note that this issue does not occur for charms [2], and it doesn't occur if a more general token is generated instead:

```
charmcraft login --export=secrets-waltz.auth \
      --permission=package-view-revisions \
      --permission=package-manage --ttl=15780000
export CHARMCRAFT_AUTH=`cat ./secrets-waltz.auth`
```

### Expected Result:

No errors should have been encountered while uploading the bundle.

### Actual Result:

```
Store operation failed:
- permission-required: Package access not allowed
```

### Environment:

node: ubuntu-latest (github action)
charmcraft version: 2.0.0

### Additional Context:
...add any other context about the problem here. If applicable, add screenshots to help explain...

[1] https://github.com/finos/waltz-juju-bundle/runs/7653817523?check_suite_focus=true
[2] https://github.com/finos/waltz-juju-bundle/runs/7652643239?check_suite_focus=true

**Comment by jnsgruk** [comment]
@Facundobatista might be able to help here

**Comment by maoo** [comment]
Thanks @facundobatista ! Is there any ETA for the fix?

**Comment by facundobatista** [comment]
Hello @maoo! No idea, sorry :(. You'd need to contact Store people about this.

**Comment by maoo** [comment]
Thanks for your help @facundobatista ! I'll follow up with my contacts at Canonical.

**Comment by pedroleaoc** [comment]
Hey folks, so this is a confirmed bug and there is someone working on fixing it [as we speak](https://bugs.launchpad.net/snapstore-server/+bug/1977727). A workaround for the time being is to generate a token without limiting it to the bundle
```
charmcraft login --export=secrets-waltz.auth \
      --permission=package-manage --ttl=15780000
export CHARMCRAFT_AUTH=`cat ./secrets-waltz.auth`
```
With the implication, of course, it's a quite permissive token.

**Comment by maoo** [comment]
Thanks @pedroleaoc , good to know that there is a workaround . Do you have an ETA (days, weeks, months) for the resolution, so we can decide whether it's best to apply the workaround now, instead of waiting for the fix? TY!

**Comment by pedroleaoc** [comment]
Hey folks, there was a fix released for this issue and the command should work with the flag now! https://bugs.launchpad.net/snapstore-server/+bug/1977727

**Comment by maoo** [comment]
Great news @pedroleaoc ! I see that all our actions are green now! Closing issue, thanks for the support!
